name: Testing for App with BrowserStack (Samsung device)
on: 
  push:
    branches: master
  pull_request:
    branches: master
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - name: Install dependencies
      run: npm install
    - name: Run all tests
      run: npm run wdio-samsung
      env:
          CI: true
          MY_USERNAME: ${{ secrets.MY_USERNAME }}
          MY_KEY: ${{ secrets.MY_KEY }}
    - uses: actions/checkout@v2
      if: always()
      with:
        repository: txt2021/appium_browserstack_tests
        ref:  report
        path: ./docs
    - name: Generate Allure Report
      if: always()
      run: npm run report-generate
    - uses: actions/upload-artifact@v2
      if: always()
      with:
        name: report
        path: allure-report/
        retention-days: 30
    - name: Push to repository
      uses: cpina/github-action-push-to-another-repository@main
      if: always()
      env:
        API_TOKEN_GITHUB: ${{ secrets.ACTIONS_TOKEN }}
      with:
        source-directory: 'allure-report'
        destination-github-username: 'txt2021'
        destination-repository-name: 'appium_browserstack_tests'
        user-email: txt2021@gmail.com
        target-branch: report




